# API- application programming interface

In [121]:
from numpy import polyadd
import pandas as pd

import requests

api_url = 'https://www.ncei.noaa.gov/cdo-web/api/v2/datacategories'
headers = {
    'token' : 'NcFrgbbBbhbTNLTFAHmmCcnqsmItgfOZ'
}
params = {
    'startdate': '1970-10-03',
    'enddate': '2012-09-10'
}
response = requests.get(api_url, headers=headers, params=params)
response.json()

{'metadata': {'resultset': {'offset': 1, 'count': 42, 'limit': 25}},
 'results': [{'name': 'Annual Agricultural', 'id': 'ANNAGR'},
  {'name': 'Annual Degree Days', 'id': 'ANNDD'},
  {'name': 'Annual Precipitation', 'id': 'ANNPRCP'},
  {'name': 'Annual Temperature', 'id': 'ANNTEMP'},
  {'name': 'Autumn Agricultural', 'id': 'AUAGR'},
  {'name': 'Autumn Degree Days', 'id': 'AUDD'},
  {'name': 'Autumn Precipitation', 'id': 'AUPRCP'},
  {'name': 'Autumn Temperature', 'id': 'AUTEMP'},
  {'name': 'Computed', 'id': 'COMP'},
  {'name': 'Computed Agricultural', 'id': 'COMPAGR'},
  {'name': 'Degree Days', 'id': 'DD'},
  {'name': 'Dual-Pol Moments', 'id': 'DUALPOLMOMENT'},
  {'name': 'Echo Tops', 'id': 'ECHOTOP'},
  {'name': 'Evaporation', 'id': 'EVAP'},
  {'name': 'Hydrometeor Type', 'id': 'HYDROMETEOR'},
  {'name': 'Land', 'id': 'LAND'},
  {'name': 'Miscellany', 'id': 'MISC'},
  {'name': 'Other', 'id': 'OTHER'},
  {'name': 'Overlay', 'id': 'OVERLAY'},
  {'name': 'Precipitation', 'id': 'PRCP'},
  {'name': 'Pressure', 'id': 'PRES'},
  {'name': 'Reflectivity', 'id': 'REFLECTIVITY'},
  {'name': 'Sky cover & clouds', 'id': 'SKY'},
  {'name': 'Spring Agricultural', 'id': 'SPAGR'},
  {'name': 'Spring Degree Days', 'id': 'SPDD'}]}

In [122]:
def make_request(endpoint, payload=None):
  return requests.get(
      f'https://www.ncei.noaa.gov/cdo-web/api/v2/{endpoint}',
      headers={
          'token' :'NcFrgbbBbhbTNLTFAHmmCcnqsmItgfOZ',
      },
      params=payload
  )
response2 = make_request
response.json()

{'metadata': {'resultset': {'offset': 1, 'count': 42, 'limit': 25}},
 'results': [{'name': 'Annual Agricultural', 'id': 'ANNAGR'},
  {'name': 'Annual Degree Days', 'id': 'ANNDD'},
  {'name': 'Annual Precipitation', 'id': 'ANNPRCP'},
  {'name': 'Annual Temperature', 'id': 'ANNTEMP'},
  {'name': 'Autumn Agricultural', 'id': 'AUAGR'},
  {'name': 'Autumn Degree Days', 'id': 'AUDD'},
  {'name': 'Autumn Precipitation', 'id': 'AUPRCP'},
  {'name': 'Autumn Temperature', 'id': 'AUTEMP'},
  {'name': 'Computed', 'id': 'COMP'},
  {'name': 'Computed Agricultural', 'id': 'COMPAGR'},
  {'name': 'Degree Days', 'id': 'DD'},
  {'name': 'Dual-Pol Moments', 'id': 'DUALPOLMOMENT'},
  {'name': 'Echo Tops', 'id': 'ECHOTOP'},
  {'name': 'Evaporation', 'id': 'EVAP'},
  {'name': 'Hydrometeor Type', 'id': 'HYDROMETEOR'},
  {'name': 'Land', 'id': 'LAND'},
  {'name': 'Miscellany', 'id': 'MISC'},
  {'name': 'Other', 'id': 'OTHER'},
  {'name': 'Overlay', 'id': 'OVERLAY'},
  {'name': 'Precipitation', 'id': 'PRCP'},
  {'name': 'Pressure', 'id': 'PRES'},
  {'name': 'Reflectivity', 'id': 'REFLECTIVITY'},
  {'name': 'Sky cover & clouds', 'id': 'SKY'},
  {'name': 'Spring Agricultural', 'id': 'SPAGR'},
  {'name': 'Spring Degree Days', 'id': 'SPDD'}]}

In [123]:
import datetime
from IPython import display

past = datetime.date(2026, 1, 1)
end = datetime.date(2026, 4, 1)

results = []

while past < end:
  display.clear_output(wait=True)
  display.display(f'Gathering data for {str(past)}')

  response2 = make_request(
      endpoint='data',
      payload={
          'datasetid': 'GHCND',
          'locationid' : 'CITY:US360019',
          'startdate': past,
          'enddate': past,
          'units': 'metric',
          'limit': 1000
      }
  )
  if response2.ok:
    results.extend(response2.json().get('results', []))
  past += datetime.timedelta(days=1)

'Gathering data for 2026-03-31'

In [124]:
df = pd.DataFrame(results)
df.head(20)

                   date datatype            station attributes  value
0   2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0003   ,,N,0730    0.8
1   2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
2   2026-01-01T00:00:00     WESF  GHCND:US1NJBG0003   ,,N,0730    0.8
3   2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0015   ,,N,0930    0.5
4   2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0015   ,,N,0930    5.0
5   2026-01-01T00:00:00     WESF  GHCND:US1NJBG0015   ,,N,0930    0.3
6   2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0018   ,,N,0900    0.3
7   2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0018   ,,N,0900    3.0
8   2026-01-01T00:00:00     SNWD  GHCND:US1NJBG0018   ,,N,0900    3.0
9   2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0023   ,,N,0800    0.5
10  2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0023   ,,N,0800   13.0
11  2026-01-01T00:00:00     SNWD  GHCND:US1NJBG0023   ,,N,0800   64.0
12  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0030   ,,N,0700    1.0
13  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0039   ,,N,0700    0.8
14  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0043   ,,N,1630    0.3
15  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0060   ,,N,0800    1.0
16  2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0060   ,,N,0800   13.0
17  2026-01-01T00:00:00     WESF  GHCND:US1NJBG0060   ,,N,0800    0.8
18  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0064   ,,N,0730    1.3
19  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0070   ,,N,0830    0.5

In [125]:
df.to_excel('NY_weather_2026_01:04.xlsx', index=False)

In [126]:
df1 = pd.read_excel('NY_weather_2026_01:04.xlsx')
df1.head()

                  date datatype            station attributes  value
0  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0003   ,,N,0730    0.8
1  2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
2  2026-01-01T00:00:00     WESF  GHCND:US1NJBG0003   ,,N,0730    0.8
3  2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0015   ,,N,0930    0.5
4  2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0015   ,,N,0930    5.0

In [127]:
df['station'].describe()

count                 16461
unique                  104
top       GHCND:USW00094789
freq                    730
Name: station, dtype: object

In [128]:
# Df dan ma'lumotlarni ajratib olish
import os
import kagglehub
path = kagglehub.dataset_download("jessicali9530/animal-crossing-new-horizons-nookplaza-dataset")

print('Dataset path: ', path)
print("Files: ", os.listdir(path))

df2 = pd.read_csv(os.path.join(path, 'art.csv'))
df2.describe()

df2.to_excel('animal_art.xlsx')

Using Colab cache for faster access to the 'animal-crossing-new-horizons-nookplaza-dataset' dataset.
Dataset path:  /kaggle/input/animal-crossing-new-horizons-nookplaza-dataset
Files:  ['construction.csv', 'bottoms.csv', 'accessories.csv', 'insects.csv', 'floors.csv', 'shoes.csv', 'wall-mounted.csv', 'achievements.csv', 'umbrellas.csv', 'rugs.csv', 'housewares.csv', 'art.csv', 'reactions.csv', 'miscellaneous.csv', 'dress-up.csv', 'photos.csv', 'bags.csv', 'villagers.csv', 'recipes.csv', 'socks.csv', 'fossils.csv', 'fencing.csv', 'tops.csv', 'wallpaper.csv', 'music.csv', 'posters.csv', 'other.csv', 'headwear.csv', 'tools.csv', 'fish.csv']

In [129]:
df2.head()

,Name,Genuine,Category,Buy,Sell,Color 1,Color 2,Size,Real Artwork Title,Artist,...,HHA Series,HHA Set,Interact,Tag,Speaker Type,Lighting Type,Catalog,Filename,Internal ID,Unique Entry ID
0,academic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianMan,12619,xfTf9sfyLkxHQEz4u
1,academic painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianManFake,12620,5KNFAo3LkdTTJPQkd
2,amazing painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatch,56,Sg6MCSG3m9tvjGWoj
3,amazing painting,No,Wall-mounted,4980,0,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatchFake,55,vc2Ebu4Pkn443zYiN
4,ancient statue,Yes,Miscellaneous,4980,1245,NaN,NaN,1x1,"Jōmon Period ""Dogū"" Figurine Shakōki-dogū","Artist Unknown, 1000-400 BCE, Fired pottery",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureDoguu,1337,zpAsguge9Yb29ksjS

**Ustunlarni kesib olish (Slicing)**

In [130]:
df2[['Buy', 'Sell']]

     Buy  Sell
0   4980  1245
1   4980     0
2   4980  1245
3   4980     0
4   4980  1245
..   ...   ...
65  4980  1245
66  4980     0
67  4980  1245
68  4980     0
69  4980  1245

[70 rows x 2 columns]

In [131]:
df2.shape

(70, 26)

In [132]:
# Agar col bilan boshlangan hamma ustublarni ajratib oladi
df2[
    ['Sell', 'Buy']
    + [col for col in df.columns if col.startswith('Col')]
]

    Sell   Buy
0   1245  4980
1      0  4980
2   1245  4980
3      0  4980
4   1245  4980
..   ...   ...
65  1245  4980
66     0  4980
67  1245  4980
68     0  4980
69  1245  4980

[70 rows x 2 columns]

**Qatorlarni kesib olish (Slicing)**

In [133]:
df2[:10] [['Sell', 'Buy']] # 2 ta tanlab olingan ustunlardan birinchi qatordan 10chi qatorgacha mavjud ma'lumotlarni ajratib oladi

   Sell   Buy
0  1245  4980
1     0  4980
2  1245  4980
3     0  4980
4  1245  4980
5     0  4980
6  1245  4980
7     0  4980
8  1245  4980
9     0  4980

In [134]:
df2['Sell'] [10:101]

10    1245
11    1245
12    1245
13       0
14    1245
15    1245
16    1245
17       0
18    1245
19    1245
20       0
21    1245
22    1245
23       0
24    1245
25    1245
26       0
27    1245
28       0
29    1245
30    1245
31       0
32    1245
33       0
34    1245
35    1245
36       0
37    1245
38    1245
39    1245
40    1245
41       0
42    1245
43       0
44    1245
45       0
46    1245
47       0
48    1245
49       0
50    1245
51       0
52    1245
53    1245
54       0
55    1245
56       0
57    1245
58    1245
59       0
60    1245
61    1245
62       0
63    1245
64       0
65    1245
66       0
67    1245
68       0
69    1245
Name: Sell, dtype: int64

In [135]:
# 2 ta df ni bir biriga solishtirish

df2['Sell'] [0:101].equals(df2['Buy'] [:]) # 2 ta dataframe teng emas
df2['Sell'] [0:101].equals(df2['Sell'] [:]) # 2 ta dataframe teng

True

In [136]:
df2['Filename'].str.lower()
# df2['Filename']

0         ftrartvitruvianman
1     ftrartvitruvianmanfake
2           ftrartnightwatch
3       ftrartnightwatchfake
4          ftrsculpturedoguu
               ...
65              ftrartfuujin
66          ftrartfuujinfake
67        ftrartpearlearring
68    ftrartpearlearringfake
69      ftrartlibertyleading
Name: Filename, Length: 70, dtype: object

In [137]:
df2[10:100] ['Filename'] = df2[10:100] ['Filename'].str.lower()

/tmp/ipykernel_9687/4068214480.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2[10:100] ['Filename'] = df2[10:100] ['Filename'].str.lower()
/tmp/ipykernel_9687/4068214480.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[10:100] ['Filename'] = df2[10:100] ['Filename'].str.lower()

In [138]:
df2.loc[10:12, 'Filename'] = df2.loc[10:12, 'Filename'].str.lower() # Faqat tanlagan qator va ustunimizdagi values kichik harflarga almashadi
df2.loc[10:12, 'Filename']

10          ftrartsundayon
11          ftrartgleaners
12    ftrartajisaisoukeizu
Name: Filename, dtype: object

In [139]:
df2.loc[10:12, ['Filename', 'Category']]

                Filename      Category
10        ftrartsundayon  Wall-mounted
11        ftrartgleaners  Wall-mounted
12  ftrartajisaisoukeizu  Wall-mounted

In [140]:
df2.head(15)

,Name,Genuine,Category,Buy,Sell,Color 1,Color 2,Size,Real Artwork Title,Artist,...,HHA Series,HHA Set,Interact,Tag,Speaker Type,Lighting Type,Catalog,Filename,Internal ID,Unique Entry ID
0,academic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianMan,12619,xfTf9sfyLkxHQEz4u
1,academic painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianManFake,12620,5KNFAo3LkdTTJPQkd
2,amazing painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatch,56,Sg6MCSG3m9tvjGWoj
3,amazing painting,No,Wall-mounted,4980,0,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatchFake,55,vc2Ebu4Pkn443zYiN
4,ancient statue,Yes,Miscellaneous,4980,1245,NaN,NaN,1x1,"Jōmon Period ""Dogū"" Figurine Shakōki-dogū","Artist Unknown, 1000-400 BCE, Fired pottery",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureDoguu,1337,zpAsguge9Yb29ksjS
5,ancient statue,No,Miscellaneous,4980,0,NaN,NaN,1x1,"Jōmon Period ""Dogū"" Figurine Shakōki-dogū","Artist Unknown, 1000-400 BCE, Fired pottery",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureDoguuFake,1338,fXbsrcXirg6miBoqT
6,basic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x2,The Blue Boy,"Thomas Gainsborough, 1770, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtBlueBoy,14,Xhn8ZjtbdZeET3NXR
7,basic painting,No,Wall-mounted,4980,0,NaN,NaN,1x2,The Blue Boy,"Thomas Gainsborough, 1770, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtBlueBoyFake,13,o4px7Mx9g2Zk6NHvC
8,beautiful statue,Yes,Housewares,4980,1245,NaN,NaN,1x1,Venus de Milo,"Artist Unknown, circa 130 BCE, Marble",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureMilo,1341,iscap6FsmDZdNP5dw
9,beautiful statue,No,Housewares,4980,0,NaN,NaN,1x1,Venus de Milo,"Artist Unknown, circa 130 BCE, Marble",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureMiloFake,1342,w9vrMbhJNj6JHkznu
10,calm painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x1.5,A Sunday Afternoon on the Island of La Grande ...,"Georges Seurat, circa 1885, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,ftrartsundayon,78,7QgYY7KuhauCnS37H
11,common painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,The Gleaners,"Jean-François Millet, 1857, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,ftrartgleaners,44,GE6sppzKjqkG7sRoz
12,detailed painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x2,Ajisai Sōkeizu,"Itō Jakuchū, 18th century, Dyed silk",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,ftrartajisaisoukeizu,12622,T2QA6mqARHfToTJpQ
13,detailed painting,No,Wall-mounted,4980,0,NaN,NaN,1x2,Ajisai Sōkeizu,"Itō Jakuchū, 18th century, Dyed silk",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtAjisaisoukeizuFake,12623,m9TkAsJFFkpQ9Hr4s
14,dynamic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Thirty-Six Views of Mount Fuji The Great Wave ...,"Katsushika Hokusai, circa 1831, Woodblock print",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtKanagawaOki,38,BMBiEvuooPCwpzHj7

In [141]:
df2.iloc[10:15, [0, 2, 5, 8, -1]] # Ham qatorlar ham ustunlarning index raqamlari bo'yicha slicing qilib oladi

,Name,Category,Color 1,Real Artwork Title,Unique Entry ID
10,calm painting,Wall-mounted,NaN,A Sunday Afternoon on the Island of La Grande ...,7QgYY7KuhauCnS37H
11,common painting,Wall-mounted,NaN,The Gleaners,GE6sppzKjqkG7sRoz
12,detailed painting,Wall-mounted,NaN,Ajisai Sōkeizu,T2QA6mqARHfToTJpQ
13,detailed painting,Wall-mounted,NaN,Ajisai Sōkeizu,m9TkAsJFFkpQ9Hr4s
14,dynamic painting,Wall-mounted,NaN,Thirty-Six Views of Mount Fuji The Great Wave ...,BMBiEvuooPCwpzHj7

In [142]:
df.columns.sort_values()

Index(['attributes', 'datatype', 'date', 'station', 'value'], dtype='object')

In [143]:
df2.iloc[10:15, 0:10] # Ham qatorlar ham ustunlarning index raqamlari bo'yicha slicing qilib oladi

,Name,Genuine,Category,Buy,Sell,Color 1,Color 2,Size,Real Artwork Title,Artist
10,calm painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x1.5,A Sunday Afternoon on the Island of La Grande ...,"Georges Seurat, circa 1885, Oil on canvas"
11,common painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,The Gleaners,"Jean-François Millet, 1857, Oil on canvas"
12,detailed painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x2,Ajisai Sōkeizu,"Itō Jakuchū, 18th century, Dyed silk"
13,detailed painting,No,Wall-mounted,4980,0,NaN,NaN,1x2,Ajisai Sōkeizu,"Itō Jakuchū, 18th century, Dyed silk"
14,dynamic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Thirty-Six Views of Mount Fuji The Great Wave ...,"Katsushika Hokusai, circa 1831, Woodblock print"

In [144]:
# Qator va ustundagi aniq bir qiymatni (cell) ni inclusive ajratib olish

df2.at[10, 'Name']

'calm painting'

In [145]:
# Qator va ustundagi aniq bir qiymatni (cell) ni ustunning indexi (.iat) orqali ajratib olish

df2.iat[10, 0]

'calm painting'

In [146]:
# Filterlash, Masking qilish (Boolean orqali)
df2['Buy']>150

0     True
1     True
2     True
3     True
4     True
      ...
65    True
66    True
67    True
68    True
69    True
Name: Buy, Length: 70, dtype: bool

In [147]:
mask = df2['Buy']>=4980 # 4980 dan kichik qiymatlandagi hamma ma'lumotlarni filter qilib oladi
df2[mask]

,Name,Genuine,Category,Buy,Sell,Color 1,Color 2,Size,Real Artwork Title,Artist,...,HHA Series,HHA Set,Interact,Tag,Speaker Type,Lighting Type,Catalog,Filename,Internal ID,Unique Entry ID
0,academic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianMan,12619,xfTf9sfyLkxHQEz4u
1,academic painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianManFake,12620,5KNFAo3LkdTTJPQkd
2,amazing painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatch,56,Sg6MCSG3m9tvjGWoj
3,amazing painting,No,Wall-mounted,4980,0,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatchFake,55,vc2Ebu4Pkn443zYiN
4,ancient statue,Yes,Miscellaneous,4980,1245,NaN,NaN,1x1,"Jōmon Period ""Dogū"" Figurine Shakōki-dogū","Artist Unknown, 1000-400 BCE, Fired pottery",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureDoguu,1337,zpAsguge9Yb29ksjS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,wild painting right half,Yes,Housewares,4980,1245,NaN,NaN,2x1,Folding Screen of Fūjin and Raijin,"Tawaraya Sōtatsu, 17th century, Gold leaf and ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtFuujin,76,rcXt6qMXZh9jj4ojN
66,wild painting right half,No,Housewares,4980,0,NaN,NaN,2x1,Folding Screen of Fūjin and Raijin,"Tawaraya Sōtatsu, 17th century, Gold leaf and ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtFuujinFake,75,aKefsi2sySXJkzPLo
67,wistful painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Girl with a Pearl Earring,"Johannes Vermeer, circa 1665, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtPearlEarring,28,Mupx2ny4sM3Kbfs3v
68,wistful painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Girl with a Pearl Earring,"Johannes Vermeer, circa 1665, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtPearlEarringFake,27,c7zw6f8Dbe5h9oJni
69,worthy painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x1.5,Liberty Leading the People,"Eugène Delacroix, 1830, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtLibertyLeading,68,8R3LhTWJzqHmPPPvK

In [148]:
df2[df2.Buy>=4980] # Yuqoridagi bilan bir xil

,Name,Genuine,Category,Buy,Sell,Color 1,Color 2,Size,Real Artwork Title,Artist,...,HHA Series,HHA Set,Interact,Tag,Speaker Type,Lighting Type,Catalog,Filename,Internal ID,Unique Entry ID
0,academic painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianMan,12619,xfTf9sfyLkxHQEz4u
1,academic painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Vitruvian Man,"Leonardo da Vinci, circa 1487, Pen and ink on ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtVitruvianManFake,12620,5KNFAo3LkdTTJPQkd
2,amazing painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatch,56,Sg6MCSG3m9tvjGWoj
3,amazing painting,No,Wall-mounted,4980,0,NaN,NaN,2x2,The Night Watch,"Rembrandt van Rijn, 1642, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtNightWatchFake,55,vc2Ebu4Pkn443zYiN
4,ancient statue,Yes,Miscellaneous,4980,1245,NaN,NaN,1x1,"Jōmon Period ""Dogū"" Figurine Shakōki-dogū","Artist Unknown, 1000-400 BCE, Fired pottery",...,NaN,NaN,No,Sculpture,Does not play music,No lighting,Not for sale,FtrSculptureDoguu,1337,zpAsguge9Yb29ksjS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,wild painting right half,Yes,Housewares,4980,1245,NaN,NaN,2x1,Folding Screen of Fūjin and Raijin,"Tawaraya Sōtatsu, 17th century, Gold leaf and ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtFuujin,76,rcXt6qMXZh9jj4ojN
66,wild painting right half,No,Housewares,4980,0,NaN,NaN,2x1,Folding Screen of Fūjin and Raijin,"Tawaraya Sōtatsu, 17th century, Gold leaf and ...",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtFuujinFake,75,aKefsi2sySXJkzPLo
67,wistful painting,Yes,Wall-mounted,4980,1245,NaN,NaN,1x1,Girl with a Pearl Earring,"Johannes Vermeer, circa 1665, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtPearlEarring,28,Mupx2ny4sM3Kbfs3v
68,wistful painting,No,Wall-mounted,4980,0,NaN,NaN,1x1,Girl with a Pearl Earring,"Johannes Vermeer, circa 1665, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtPearlEarringFake,27,c7zw6f8Dbe5h9oJni
69,worthy painting,Yes,Wall-mounted,4980,1245,NaN,NaN,2x1.5,Liberty Leading the People,"Eugène Delacroix, 1830, Oil on canvas",...,NaN,NaN,No,Picture,Does not play music,No lighting,Not for sale,FtrArtLibertyLeading,68,8R3LhTWJzqHmPPPvK

In [149]:
df2.loc[
    (df2.Size=='1x1') & (df2['Tag'] == 'Picture'),
    ['Category', 'Sell', 'Tag']
]

        Category  Sell      Tag
0   Wall-mounted  1245  Picture
1   Wall-mounted     0  Picture
11  Wall-mounted  1245  Picture
14  Wall-mounted  1245  Picture
16  Wall-mounted  1245  Picture
17  Wall-mounted     0  Picture
18  Wall-mounted  1245  Picture
21  Wall-mounted  1245  Picture
27  Wall-mounted  1245  Picture
28  Wall-mounted     0  Picture
29  Wall-mounted  1245  Picture
38  Wall-mounted  1245  Picture
40  Wall-mounted  1245  Picture
41  Wall-mounted     0  Picture
46  Wall-mounted  1245  Picture
47  Wall-mounted     0  Picture
50  Wall-mounted  1245  Picture
51  Wall-mounted     0  Picture
52  Wall-mounted  1245  Picture
57  Wall-mounted  1245  Picture
67  Wall-mounted  1245  Picture
68  Wall-mounted     0  Picture

In [150]:
df3 = pd.read_excel('/content/NY_weather_2026_01:04.xlsx')
df3

                      date datatype            station attributes  value
0      2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0003   ,,N,0730    0.8
1      2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
2      2026-01-01T00:00:00     WESF  GHCND:US1NJBG0003   ,,N,0730    0.8
3      2026-01-01T00:00:00     PRCP  GHCND:US1NJBG0015   ,,N,0930    0.5
4      2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0015   ,,N,0930    5.0
...                    ...      ...                ...        ...    ...
16456  2026-03-31T00:00:00     TMAX  GHCND:USW00094741       ,,d,   26.7
16457  2026-03-31T00:00:00     TMIN  GHCND:USW00094741       ,,d,   15.6
16458  2026-03-31T00:00:00     PRCP  GHCND:USW00094745   ,,d,2400    0.8
16459  2026-03-31T00:00:00     TMAX  GHCND:USW00094745   ,,d,2400   25.6
16460  2026-03-31T00:00:00     TMIN  GHCND:USW00094745   ,,d,2400   11.7

[16461 rows x 5 columns]

In [151]:
df3.loc[
    (df3['datatype']=='SNOW') & (df3['station']=='GHCND:US1NJBG0003') & (df3['value']>=0.0),
    ['date', 'attributes']
]

                      date attributes
1      2026-01-01T00:00:00   ,,N,0730
7317   2026-02-07T00:00:00   ,,N,0730
8927   2026-02-16T00:00:00   ,,N,0730
9810   2026-02-23T00:00:00   ,,N,0730
10033  2026-02-24T00:00:00   ,,N,0730
10239  2026-02-25T00:00:00   ,,N,0730
11530  2026-03-04T00:00:00  T,,N,0730
13181  2026-03-13T00:00:00  T,,N,0730

In [152]:
df3.loc[
    df3.value.between(5.1, 500.0) &  (df3['datatype']=='SNOW')
   ]

                      date datatype            station attributes  value
1      2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
10     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0023   ,,N,0800   13.0
16     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0060   ,,N,0800   13.0
21     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0018   ,,N,0700   20.0
24     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0024   ,,N,2359   13.0
...                    ...      ...                ...        ...    ...
10557  2026-02-26T00:00:00     SNOW  GHCND:US1NYQN0039   ,,N,0530   30.0
10572  2026-02-26T00:00:00     SNOW  GHCND:US1NYSF0089   ,,N,0800   51.0
10574  2026-02-26T00:00:00     SNOW  GHCND:US1NYSF0092   ,,N,0800   64.0
10597  2026-02-26T00:00:00     SNOW  GHCND:USC00284987       ,,7,   28.0
10608  2026-02-26T00:00:00     SNOW  GHCND:USC00301309       ,,H,   33.0

[411 rows x 5 columns]

In [153]:
df3.loc[
    df3.value.between(5.1, 500.0) & df3.datatype.isin(['SNOW', 'TMAX'])
]

                      date datatype            station attributes  value
1      2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
10     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0023   ,,N,0800   13.0
16     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0060   ,,N,0800   13.0
21     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0018   ,,N,0700   20.0
24     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0024   ,,N,2359   13.0
...                    ...      ...                ...        ...    ...
16446  2026-03-31T00:00:00     TMAX  GHCND:USC00308577   ,,H,0800   20.0
16450  2026-03-31T00:00:00     TMAX  GHCND:USW00054743       ,,d,   26.7
16453  2026-03-31T00:00:00     TMAX  GHCND:USW00054787       ,,d,   20.0
16456  2026-03-31T00:00:00     TMAX  GHCND:USW00094741       ,,d,   26.7
16459  2026-03-31T00:00:00     TMAX  GHCND:USW00094745   ,,d,2400   25.6

[929 rows x 5 columns]

In [154]:
# Bundan oldingi kod bilan bir xil natija beradi
df3.loc[
    df3.value.between(5.1, 500.0) &  (df3['datatype'].isin(['SNOW', 'TMAX']))
   ]

                      date datatype            station attributes  value
1      2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0003   ,,N,0730    8.0
10     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0023   ,,N,0800   13.0
16     2026-01-01T00:00:00     SNOW  GHCND:US1NJBG0060   ,,N,0800   13.0
21     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0018   ,,N,0700   20.0
24     2026-01-01T00:00:00     SNOW  GHCND:US1NJES0024   ,,N,2359   13.0
...                    ...      ...                ...        ...    ...
16446  2026-03-31T00:00:00     TMAX  GHCND:USC00308577   ,,H,0800   20.0
16450  2026-03-31T00:00:00     TMAX  GHCND:USW00054743       ,,d,   26.7
16453  2026-03-31T00:00:00     TMAX  GHCND:USW00054787       ,,d,   20.0
16456  2026-03-31T00:00:00     TMAX  GHCND:USW00094741       ,,d,   26.7
16459  2026-03-31T00:00:00     TMAX  GHCND:USW00094745   ,,d,2400   25.6

[929 rows x 5 columns]

In [155]:
[df3['value'].idxmin(), df3['value'].idxmax()] # Maximum va minimum qiymatlar qaysi indexda ekanligini aniqlash

[6059, 9905]

In [156]:
min = df3['value'] [7270] # Yoki min = df3['value'].max()
min

np.float64(8.9)

In [157]:
max = df3['value'] [12218]
max

np.float64(0.8)

In [158]:
df3.loc[
    [df3['value'].idxmin(), df3['value'].idxmax()],
    ['attributes', 'datatype', 'value']
]

     attributes datatype  value
6059   ,,7,0700     TMIN  -18.3
9905   ,,N,0800     SNOW  584.0

In [159]:
# Qo'shimcha ustun va uning qiymatlarini qo'shib qo'yish

df3_minmax = df3.loc[
    [df3['value'].idxmin(), df3['value'].idxmax()],
    ['attributes', 'datatype', 'value']
]

df3_minmax['order'] = ['min', 'max']
df3_minmax

     attributes datatype  value order
6059   ,,7,0700     TMIN  -18.3   min
9905   ,,N,0800     SNOW  584.0   max

In [160]:
# Shunchaki filter() methodidan ham foydalanish mn faat bunda list ko'rinishida olinadi

df3.filter(items=['datatype', 'value']).head()

  datatype  value
0     PRCP    0.8
1     SNOW    8.0
2     WESF    0.8
3     PRCP    0.5
4     SNOW    5.0

In [161]:
df3.filter(like='da').head() # da deb boshlangan har bir ustunni filter qilib oladi

                  date datatype
0  2026-01-01T00:00:00     PRCP
1  2026-01-01T00:00:00     SNOW
2  2026-01-01T00:00:00     WESF
3  2026-01-01T00:00:00     PRCP
4  2026-01-01T00:00:00     SNOW

In [162]:
df3.filter(regex=r'^d').head() # T harfi bilan boshlanadigan har bir ustunni filterlash

                  date datatype
0  2026-01-01T00:00:00     PRCP
1  2026-01-01T00:00:00     SNOW
2  2026-01-01T00:00:00     WESF
3  2026-01-01T00:00:00     PRCP
4  2026-01-01T00:00:00     SNOW

In [173]:
# df ga yangi qo'shimcha ustun qo'shish

df3['N_ustun'] = 'US_API'
df3.head()
df3.tail(20) # df ning eng oxiridagi 20 ta qatorni ko'rsatish

,date,datatype,station,attributes,value,N_ustun,value_negative
16441,2026-03-31T00:00:00,SNWD,GHCND:USC00301309,",,H,0700",0.0,US_API,False
16442,2026-03-31T00:00:00,TMAX,GHCND:USC00301309,",,H,0700",21.7,US_API,False
16443,2026-03-31T00:00:00,TMIN,GHCND:USC00301309,",,H,0700",6.7,US_API,False
16444,2026-03-31T00:00:00,TOBS,GHCND:USC00301309,",,H,0700",11.7,US_API,False
16445,2026-03-31T00:00:00,PRCP,GHCND:USC00308577,",,H,0800",0.5,US_API,False
16446,2026-03-31T00:00:00,TMAX,GHCND:USC00308577,",,H,0800",20.0,US_API,False
16447,2026-03-31T00:00:00,TMIN,GHCND:USC00308577,",,H,0800",8.9,US_API,False
16448,2026-03-31T00:00:00,TOBS,GHCND:USC00308577,",,H,0800",12.8,US_API,False
16449,2026-03-31T00:00:00,PRCP,GHCND:USW00054743,",,d,",3.0,US_API,False
16450,2026-03-31T00:00:00,TMAX,GHCND:USW00054743,",,d,",26.7,US_API,False
16451,2026-03-31T00:00:00,TMIN,GHCND:USW00054743,",,d,",14.4,US_API,False
16452,2026-03-31T00:00:00,PRCP,GHCND:USW00054787,"T,,d,",0.0,US_API,False
16453,2026-03-31T00:00:00,TMAX,GHCND:USW00054787,",,d,",20.0,US_API,False
16454,2026-03-31T00:00:00,TMIN,GHCND:USW00054787,",,d,",10.0,US_API,False
16455,2026-03-31T00:00:00,PRCP,GHCND:USW00094741,",,d,",0.3,US_API,False
16456,2026-03-31T00:00:00,TMAX,GHCND:USW00094741,",,d,",26.7,US_API,False
16457,2026-03-31T00:00:00,TMIN,GHCND:USW00094741,",,d,",15.6,US_API,False
16458,2026-03-31T00:00:00,PRCP,GHCND:USW00094745,",,d,2400",0.8,US_API,False
16459,2026-03-31T00:00:00,TMAX,GHCND:USW00094745,",,d,2400",25.6,US_API,False
16460,2026-03-31T00:00:00,TMIN,GHCND:USW00094745,",,d,2400",11.7,US_API,False

In [164]:
df3['value_negative'] = df['value'] < 0
df3.head()

,date,datatype,station,attributes,value,N_ustun,value_negative
0,2026-01-01T00:00:00,PRCP,GHCND:US1NJBG0003,",,N,0730",0.8,US_API,False
1,2026-01-01T00:00:00,SNOW,GHCND:US1NJBG0003,",,N,0730",8.0,US_API,False
2,2026-01-01T00:00:00,WESF,GHCND:US1NJBG0003,",,N,0730",0.8,US_API,False
3,2026-01-01T00:00:00,PRCP,GHCND:US1NJBG0015,",,N,0930",0.5,US_API,False
4,2026-01-01T00:00:00,SNOW,GHCND:US1NJBG0015,",,N,0930",5.0,US_API,False

In [165]:
df3['value_negative'] [7270]

np.False_

In [171]:
# Ustunda nechatadan unique valueslar borligini chiqazish

#df3['datatype'].value_counts()
df3['value_negative'].value_counts()

value_negative
False    15228
True      1233
Name: count, dtype: int64

In [172]:
false = df3[df3['value_negative'] ==False]
true = df3[df3['value_negative'] ==True]

false

,date,datatype,station,attributes,value,N_ustun,value_negative
0,2026-01-01T00:00:00,PRCP,GHCND:US1NJBG0003,",,N,0730",0.8,US_API,False
1,2026-01-01T00:00:00,SNOW,GHCND:US1NJBG0003,",,N,0730",8.0,US_API,False
2,2026-01-01T00:00:00,WESF,GHCND:US1NJBG0003,",,N,0730",0.8,US_API,False
3,2026-01-01T00:00:00,PRCP,GHCND:US1NJBG0015,",,N,0930",0.5,US_API,False
4,2026-01-01T00:00:00,SNOW,GHCND:US1NJBG0015,",,N,0930",5.0,US_API,False
...,...,...,...,...,...,...,...
16456,2026-03-31T00:00:00,TMAX,GHCND:USW00094741,",,d,",26.7,US_API,False
16457,2026-03-31T00:00:00,TMIN,GHCND:USW00094741,",,d,",15.6,US_API,False
16458,2026-03-31T00:00:00,PRCP,GHCND:USW00094745,",,d,2400",0.8,US_API,False
16459,2026-03-31T00:00:00,TMAX,GHCND:USW00094745,",,d,2400",25.6,US_API,False
16460,2026-03-31T00:00:00,TMIN,GHCND:USW00094745,",,d,2400",11.7,US_API,False

In [174]:
df3.describe() # Umumiy df ni describe qiladi
df3['value'].describe() # df ni ichidagi tanlangan ustunni describe qiladi

count    16461.000000
mean        21.972693
std         68.804270
min        -18.300000
25%          0.000000
50%          0.000000
75%          5.600000
max        584.000000
Name: value, dtype: float64