<a href="https://colab.research.google.com/github/Mirjalol1909/Sun-iy-ong/blob/main/Pandas_usage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import datetime as dt
import numpy as np # Numpay kutubxonasi jadvallar bilan ishlaganda juda hard coding talab etadi. Numpy bu numerical ko'rinishida bo'lib arraylar bn ishlatiladi
#data = np.genfromtxt('/content/sample_data/california_housing_test.csv', delimiter= ",", dtype = None, )
#data

import pandas as pd # Pandas kutubxonasida dataframe lar yani jadvallar bilan ishlanadi

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv', delimiter=',', dtype=None, encoding='UTF')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df['total_rooms'].max()

30450.0

In [ ]:
longtitude = pd.Series(df['latitude'], name= 'longtitude1')
longtitude

0       37.37
1       34.26
2       33.78
3       33.82
4       36.33
        ...
2995    34.42
2996    34.06
2997    36.30
2998    34.10
2999    34.42
Name: longtitude1, Length: 3000, dtype: float64

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
df.population.values

array([1537.,  809., 1484., ...,  693.,   46.,  753.])

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=3000, step=1)

In [ ]:
idx= df.index
idx

RangeIndex(start=0, stop=3000, step=1)

In [ ]:
idx.values

array([   0,    1,    2, ..., 2997, 2998, 2999])

In [ ]:
idx.is_unique

True

In [ ]:
df.shape

(3000, 9)

In [ ]:
df + df # Integer bo'lsa 2 ga ko'payadi. Str bo'lsa so'z 2 marta takrorlanadi

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-244.10,74.74,54.0,7770.0,1322.0,3074.0,1212.0,13.2170,689400.0
1,-236.60,68.52,86.0,3020.0,620.0,1618.0,554.0,7.1980,353000.0
2,-235.62,67.56,54.0,7178.0,1014.0,2968.0,990.0,11.5868,541000.0
3,-236.72,67.64,56.0,134.0,30.0,98.0,22.0,12.2718,660000.0
4,-239.34,72.66,38.0,2482.0,488.0,1700.0,474.0,5.8750,163400.0
...,...,...,...,...,...,...,...,...,...
2995,-239.72,68.84,46.0,2900.0,1284.0,2516.0,1214.0,2.3580,450000.0
2996,-236.28,68.12,54.0,10514.0,2164.0,6992.0,2072.0,6.7812,474400.0
2997,-239.40,72.60,20.0,1912.0,402.0,1386.0,440.0,4.5790,124000.0
2998,-234.24,68.20,80.0,192.0,28.0,92.0,28.0,6.5416,325000.0
2999,-239.26,68.84,84.0,3530.0,526.0,1506.0,520.0,17.1216,1000002.0

In [ ]:
# Dictionariesdan df yaratish
pd.DataFrame([
    {'latitude':10, 'total_rooms':10},
    {'latitude':15, 'total_rooms':15},
])

   latitude  total_rooms
0        10           10
1        15           15

In [ ]:
# Numpy ni ishlatgan holda df ma'lumot yaratib olsih
data = np.arange(9).reshape(3,3)
columns = ['longtitude', 'latitude', 'total_rooms']
pd.DataFrame(data, columns=columns)

   longtitude  latitude  total_rooms
0           0         1            2
1           3         4            5
2           6         7            8

In [ ]:
# List tuple dan df yaratish
l_tup = [(n, n**2, n**3) for n in range(5)]
l_tup
pd.DataFrame(l_tup, columns= ['self', 'square', 'cube'])

   self  square  cube
0     0       0     0
1     1       1     1
2     2       4     8
3     3       9    27
4     4      16    64

In [ ]:
# df ninng ichidagi ma'lumotlarni ajratib olish
df_copy = df[['latitude', 'total_rooms']]
df_copy

      latitude  total_rooms
0        37.37       3885.0
1        34.26       1510.0
2        33.78       3589.0
3        33.82         67.0
4        36.33       1241.0
...        ...          ...
2995     34.42       1450.0
2996     34.06       5257.0
2997     36.30        956.0
2998     34.10         96.0
2999     34.42       1765.0

[3000 rows x 2 columns]

In [ ]:
# Random seed ishlatib parameterlarni o'zgarmas qilib qo'yish va df yaratish

np.random.seed(42)
df1 = pd.DataFrame(
    {
        'random': np.random.rand(5),
        'text': ['hot', 'warm', 'cool', 'cold', None],
        'truth': [np.random.choice([True, False])for _ in range(5)]
    },
    index= pd.date_range(
        end = dt.date(2025, 8, 19),
        freq = '2d',
        periods=5,
        name = 'date'
    )
)
df1

              random  text  truth
date
2025-08-11  0.374540   hot   True
2025-08-13  0.950714  warm   True
2025-08-15  0.731994  cool   True
2025-08-17  0.598658  cold   True
2025-08-19  0.156019  None  False

In [ ]:
# Ajratib olingan datani saqlab olish
df_copy.to_excel('saqlavchi1.xlsx', index = False)

In [ ]:
df_copy.shape

(3000, 2)

In [ ]:
# Excel dan ma'lumotlarni o'qish
df2 = pd.read_excel('saqlavchi1.xlsx')
df2

      latitude  total_rooms
0        37.37         3885
1        34.26         1510
2        33.78         3589
3        33.82           67
4        36.33         1241
...        ...          ...
2995     34.42         1450
2996     34.06         5257
2997     36.30          956
2998     34.10           96
2999     34.42         1765

[3000 rows x 2 columns]

In [ ]:
# csv fileni sql (db) filega connect qilib saqlab olish
import sqlite3
with sqlite3.connect('quaces.db') as connection:
  pd.read_csv('saqlavchi1.csv').to_sql(
      'saqlavchi1', connection, index=False, if_exists='replace'
  )

FileNotFoundError: [Errno 2] No such file or directory: 'saqlavchi1.csv'

In [ ]:

# Sql type lik datani o'qitish
# with sqlite3.connect('quaces.db') as connection:
#   df3 = pd.read_sql('SELECT * FROM df3', connection)
# df3.sample(5)